TARGET := target/debug
BINARY_NAME := client

# Default target
all: build move

# Build the project with Cargo
build:
	cargo build

# Move the binary to the root directory
move:
	cp $(TARGET)/$(BINARY_NAME) ./

# Clean up build files
clean:
	cargo clean

# Phony targets so they don't conflict with any files named 'all', 'build', 'move', or 'clean'
.PHONY: all build move clean
